import { FormNode, FormAgentState } from "../types/form";

export const defaultFormTree: FormNode = {
  node_id: "root_form",
  node_type: "form",
  label: "Newgen Enterprise Loan Application System",
  children: [
    {
      node_id: "tab_eligibility",
      node_type: "tab",
      label: "Check Eligibility",
      children: [
        {
          node_id: "sec_sourcing",
          node_type: "section",
          label: "Sourcing",
          description: "Application sourcing channel, entity classification, and initial priority details",
          children: [
            {
              node_id: "entity",
              node_type: "field",
              label: "Entity",
              field_type: "select",
              options: ["Individual", "Corporate Entity", "Partnership Firm", "LLP"],
              value: "Select",
            },
            {
              node_id: "income_type",
              node_type: "field",
              label: "Income Type",
              field_type: "select",
              options: ["Salaried", "Self-Employed Professional", "Self-Employed Non-Professional", "Business Income"],
              value: "Select",
            },
            {
              node_id: "channel",
              node_type: "field",
              label: "Channel",
              field_type: "select",
              required: true,
              options: ["Branch Walkin", "Direct Sales Agent (DSA)", "Online Portal", "Relationship Manager"],
              value: "Branch Walkin",
            },
            {
              node_id: "branch",
              node_type: "field",
              label: "Branch",
              field_type: "select",
              required: true,
              options: [
                "GHAZIABAD INGRAHAM INSTITUTE GHAZIABAD",
                "MUMBAI NARIMAN POINT",
                "NEW DELHI CONNAUGHT PLACE",
                "BANGALORE MG ROAD",
                "HYDERABAD HITEC CITY",
              ],
              value: "GHAZIABAD INGRAHAM INSTITUTE GHAZIABAD",
            },
            {
              node_id: "branch_code",
              node_type: "field",
              label: "Branch Code",
              field_type: "select",
              options: ["GBD-1042", "MUM-2091", "DEL-3011", "BLR-4052"],
              value: "Select",
            },
            {
              node_id: "case_priority",
              node_type: "field",
              label: "Case Priority",
              field_type: "select",
              required: true,
              options: ["Low", "Medium", "High", "Urgent / Expedited"],
              value: "Medium",
            },
            {
              node_id: "status",
              node_type: "field",
              label: "Status",
              field_type: "text",
              placeholder: "Auto-generated status...",
              value: "Initiated",
            },
            {
              node_id: "identity_type",
              node_type: "field",
              label: "Identity Type",
              field_type: "select",
              options: ["PAN Card", "Aadhaar Card", "Passport", "Voter ID", "Driving License"],
              value: "Select",
            },
            {
              node_id: "btn_search_customer",
              node_type: "action_button",
              label: "Search Customer",
            },
            {
              node_id: "btn_upload_applicant",
              node_type: "action_button",
              label: "Upload Applicant Form",
            },
            {
              node_id: "marketing_consent",
              node_type: "field",
              label: "Marketing & Digital Communications Consent",
              field_type: "checkbox",
              description:
                "I hereby consent to receive marketing communications, promotional offers, and updates from Newgen Bank through email, SMS, phone calls, or other digital channels. I understand that I may withdraw consent at any time.",
              value: true,
            },
          ],
        },
        {
          node_id: "sec_aadhaar_consent",
          node_type: "section",
          label: "Aadhaar Consent",
          children: [
            {
              node_id: "full_name",
              node_type: "field",
              label: "Full Name",
              field_type: "text",
              required: true,
              placeholder: "Enter full name...",
              value: "John Doe",
            },
            {
              node_id: "mobile_number",
              node_type: "field",
              label: "Mobile Number",
              field_type: "phone",
              required: true,
              placeholder: "Enter 10-digit mobile number...",
              value: "+91 9876543210",
            },
            {
              node_id: "email_id",
              node_type: "field",
              label: "Email ID",
              field_type: "email",
              required: true,
              placeholder: "Enter email ID...",
              value: "john.doe@enterprise.com",
            },
            {
              node_id: "btn_send_consent_email",
              node_type: "action_button",
              label: "Send Consent E-mail",
            },
          ],
        },
      ],
    },
    {
      node_id: "tab_customer",
      node_type: "tab",
      label: "Customer Details",
      children: [
        {
          node_id: "sec_customer_profile",
          node_type: "section",
          label: "Primary Customer Profile",
          children: [
            {
              node_id: "cust_name",
              node_type: "field",
              label: "Customer Name",
              field_type: "text",
              required: true,
              value: "John Doe",
            },
            {
              node_id: "cust_id",
              node_type: "field",
              label: "Customer ID",
              field_type: "text",
              required: true,
              value: "CUST-10293",
            },
            {
              node_id: "gender",
              node_type: "field",
              label: "Gender",
              field_type: "select",
              options: ["Male", "Female", "Other"],
              value: "Male",
            },
            {
              node_id: "cust_email",
              node_type: "field",
              label: "Email Address",
              field_type: "email",
              required: true,
              value: "john.doe@enterprise.com",
            },
            {
              node_id: "cust_phone",
              node_type: "field",
              label: "Phone Number",
              field_type: "phone",
              value: "+91 9876543210",
            },
          ],
        },
      ],
    },
    {
      node_id: "tab_financial",
      node_type: "tab",
      label: "Financial Info",
      children: [
        {
          node_id: "sec_financial_summary",
          node_type: "section",
          label: "Financial Assessment & Credit Score",
          children: [
            {
              node_id: "annual_income",
              node_type: "field",
              label: "Annual Income (INR)",
              field_type: "number",
              required: true,
              value: 2400000,
            },
            {
              node_id: "cibil_score",
              node_type: "field",
              label: "CIBIL / Credit Score",
              field_type: "number",
              required: true,
              value: 785,
            },
            {
              node_id: "acc_balance",
              node_type: "field",
              label: "Account Balance",
              field_type: "number",
              readonly: true,
              description: "System computed ledger balance (Read-Only)",
              value: 1250000,
            },
          ],
        },
      ],
    },
    {
      node_id: "tab_collateral",
      node_type: "tab",
      label: "Collateral",
      children: [
        {
          node_id: "sec_collateral_details",
          node_type: "section",
          label: "Collateral Security & Asset Valuation",
          children: [
            {
              node_id: "collateral_type",
              node_type: "field",
              label: "Collateral Type",
              field_type: "select",
              options: ["Residential Property", "Commercial Property", "Fixed Deposit", "Gold / Sovereign Bonds"],
              value: "Residential Property",
            },
            {
              node_id: "asset_value",
              node_type: "field",
              label: "Estimated Asset Value (INR)",
              field_type: "number",
              value: 8500000,
            },
          ],
        },
      ],
    },
    {
      node_id: "tab_loan",
      node_type: "tab",
      label: "Loan Info",
      children: [
        {
          node_id: "sec_loan_structure",
          node_type: "section",
          label: "Loan Terms & Disbursement",
          children: [
            {
              node_id: "requested_amount",
              node_type: "field",
              label: "Requested Amount (INR)",
              field_type: "number",
              required: true,
              value: 5000000,
            },
            {
              node_id: "tenure_months",
              node_type: "field",
              label: "Tenure (Months)",
              field_type: "number",
              required: true,
              value: 240,
            },
            {
              node_id: "interest_rate",
              node_type: "field",
              label: "Interest Rate (%)",
              field_type: "number",
              value: 8.5,
            },
          ],
        },
      ],
    },
    {
      node_id: "tab_document",
      node_type: "tab",
      label: "Document",
      children: [
        {
          node_id: "sec_document_check",
          node_type: "section",
          label: "KYC & Income Document Checklist",
          children: [
            {
              node_id: "pan_verified",
              node_type: "field",
              label: "PAN Card Uploaded & Verified",
              field_type: "switch",
              value: true,
            },
            {
              node_id: "bank_statement_verified",
              node_type: "field",
              label: "6-Month Bank Statement Verified",
              field_type: "switch",
              value: true,
            },
          ],
        },
      ],
    },
    {
      node_id: "tab_matching",
      node_type: "tab",
      label: "Data Matching",
      children: [
        {
          node_id: "sec_data_matching",
          node_type: "section",
          label: "Dedupe & Anti-Money Laundering (AML) Screening",
          children: [
            {
              node_id: "dedupe_status",
              node_type: "field",
              label: "Dedupe Match Result",
              field_type: "select",
              options: ["No Match Found", "Possible Match", "Exact Duplicate"],
              value: "No Match Found",
            },
            {
              node_id: "aml_flag",
              node_type: "field",
              label: "AML Risk Flag",
              field_type: "select",
              options: ["Clear", "Watchlist", "High Risk"],
              value: "Clear",
            },
          ],
        },
      ],
    },
    {
      node_id: "tab_fees",
      node_type: "tab",
      label: "Fees and Charges",
      children: [
        {
          node_id: "sec_fees_breakdown",
          node_type: "section",
          label: "Processing Fees & Stamp Duty",
          children: [
            {
              node_id: "processing_fee",
              node_type: "field",
              label: "Processing Fee (INR)",
              field_type: "number",
              value: 10000,
            },
            {
              node_id: "documentation_charges",
              node_type: "field",
              label: "Documentation Charges (INR)",
              field_type: "number",
              value: 2500,
            },
          ],
        },
      ],
    },
    {
      node_id: "tab_decision",
      node_type: "tab",
      label: "Decision",
      children: [
        {
          node_id: "sec_underwriting_decision",
          node_type: "section",
          label: "Underwriting Sanction & Final Approval",
          children: [
            {
              node_id: "sanction_status",
              node_type: "field",
              label: "Sanction Status",
              field_type: "select",
              required: true,
              options: ["Pending Underwriting", "Approved", "Pre-Approved", "Declined"],
              value: "Pre-Approved",
            },
            {
              node_id: "underwriter_notes",
              node_type: "field",
              label: "Underwriter Sanction Remarks",
              field_type: "textarea",
              value: "Applicant meets all credit criteria and risk thresholds. Sanction recommended.",
            },
          ],
        },
      ],
    },
  ],
};

export const defaultFieldValues: Record<string, any> = {
  entity: "Select",
  income_type: "Select",
  channel: "Branch Walkin",
  branch: "GHAZIABAD INGRAHAM INSTITUTE GHAZIABAD",
  branch_code: "Select",
  case_priority: "Medium",
  status: "Initiated",
  identity_type: "Select",
  marketing_consent: true,
  full_name: "John Doe",
  mobile_number: "+91 9876543210",
  email_id: "john.doe@enterprise.com",
  cust_name: "John Doe",
  cust_id: "CUST-10293",
  gender: "Male",
  cust_email: "john.doe@enterprise.com",
  cust_phone: "+91 9876543210",
  annual_income: 2400000,
  cibil_score: 785,
  acc_balance: 1250000,
  collateral_type: "Residential Property",
  asset_value: 8500000,
  requested_amount: 5000000,
  tenure_months: 240,
  interest_rate: 8.5,
  pan_verified: true,
  bank_statement_verified: true,
  dedupe_status: "No Match Found",
  aml_flag: "Clear",
  processing_fee: 10000,
  documentation_charges: 2500,
  sanction_status: "Pre-Approved",
  underwriter_notes: "Applicant meets all credit criteria and risk thresholds. Sanction recommended.",
};

export const defaultFormState: FormAgentState = {
  formTree: defaultFormTree,
  fieldValues: defaultFieldValues,
  selectedTab: "tab_eligibility",
  selectedNode: null,
  conversationHistory: [],
  lastAction: null,
  isProcessing: false,
  error: null,
};
